Update main.yml
delete norm rule

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,23 +10,23 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v2
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.x'
+    # - name: Set up Python
+    #   uses: actions/setup-python@v2
+    #   with:
+    #     python-version: '3.x'
 
-    - name: Install Norminette
-      run: pip install norminette
+    # - name: Install Norminette
+    #   run: pip install norminette
 
-    - name: Run Norminette
-      run: norminette
+    # - name: Run Norminette
+    #   run: norminette
 
-    - name: Fail if Norminette finds errors
-      run: |
-        if norminette | grep -q 'Error'; then
-          echo "Norminette errors found"
-          exit 1
-        fi
+    # - name: Fail if Norminette finds errors
+    #   run: |
+    #     if norminette | grep -q 'Error'; then
+    #       echo "Norminette errors found"
+    #       exit 1
+    #     fi
 
     - name: Check for Executable and Object Files
       run: |
